version: "3.8"

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=personsjs
    ports:
      - 5432:5432
    restart: always
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    restart: always
